export const ENABLE_DEMO_LOGINS = true;

const createTaxProfile = ({
  employment = false,
  gigWork = false,
  selfEmployment = false,
  incorporatedBusiness = false,
} = {}) => ({
  employment,
  gigWork,
  selfEmployment,
  incorporatedBusiness,
});

export const demoUsers = [
  {
    id: 'demo-user-basic',
    title: 'T4 Employee',
    subtitle: 'Single employment profile',
    email: 'employee@taxvault.demo',
    password: 'Password123!',
    role: 'user',
    tone: 'blue',
    profile: {
      name: 'Anna Patel',
      userType: 'employee',
      taxProfile: createTaxProfile({ employment: true }),
      maritalStatus: 'Single',
      spouseInfo: null,
      dependents: [],
    },
  },
  {
    id: 'demo-user-gig',
    title: 'Gig Worker',
    subtitle: 'Uber / DoorDash style profile',
    email: 'gig@taxvault.demo',
    password: 'Password123!',
    role: 'user',
    tone: 'green',
    profile: {
      name: 'Rohit Sharma',
      userType: 'gig-worker',
      taxProfile: createTaxProfile({ gigWork: true }),
      maritalStatus: 'Single',
      spouseInfo: null,
      dependents: [],
      platforms: ['Uber', 'DoorDash'],
    },
  },
  {
    id: 'demo-user-self-employed',
    title: 'Self-Employed',
    subtitle: 'Freelancer / contractor',
    email: 'selfemployed@taxvault.demo',
    password: 'Password123!',
    role: 'user',
    tone: 'amber',
    profile: {
      name: 'Sarah Khan',
      userType: 'self-employed',
      taxProfile: createTaxProfile({ selfEmployment: true }),
      maritalStatus: 'Single',
      spouseInfo: null,
      dependents: [],
    },
  },
  {
    id: 'demo-user-business',
    title: 'Business Owner',
    subtitle: 'Corporation / incorporated business',
    email: 'business@taxvault.demo',
    password: 'Password123!',
    role: 'user',
    tone: 'purple',
    profile: {
      name: 'Michael Lee',
      userType: 'business',
      taxProfile: createTaxProfile({ incorporatedBusiness: true }),
      maritalStatus: 'Single',
      spouseInfo: null,
      dependents: [],
      businessName: 'Lee Consulting Inc.',
    },
  },
  {
    id: 'demo-user-mixed',
    title: 'T4 + Gig',
    subtitle: 'Employment plus side income',
    email: 'mixed@taxvault.demo',
    password: 'Password123!',
    role: 'user',
    tone: 'indigo',
    profile: {
      name: 'Aman Gill',
      userType: 'gig-worker',
      taxProfile: createTaxProfile({ employment: true, gigWork: true }),
      maritalStatus: 'Single',
      spouseInfo: null,
      dependents: [],
      platforms: ['Instacart'],
    },
  },
  {
    id: 'demo-user-spouse-1',
    title: 'Gig + Spouse T4',
    subtitle: 'Household scenario',
    email: 'gigspouset4@taxvault.demo',
    password: 'Password123!',
    role: 'user',
    tone: 'teal',
    profile: {
      name: 'Karan Mehta',
      userType: 'gig-worker',
      taxProfile: createTaxProfile({ gigWork: true }),
      maritalStatus: 'Married',
      spouseInfo: {
        name: 'Neha Mehta',
        incomeType: 'employment',
        annualIncome: '62000',
      },
      dependents: [],
      platforms: ['Uber'],
    },
  },
  {
    id: 'demo-user-spouse-2',
    title: 'T4 + Business',
    subtitle: 'Employment plus incorporated business',
    email: 't4business@taxvault.demo',
    password: 'Password123!',
    role: 'user',
    tone: 'rose',
    profile: {
      name: 'Anna Patel',
      userType: 'business',
      taxProfile: createTaxProfile({ employment: true, incorporatedBusiness: true }),
      maritalStatus: 'Single',
      spouseInfo: null,
      dependents: [],
      businessName: 'Patel Holdings Inc.',
    },
  },
  {
    id: 'demo-ca',
    title: 'CA Demo',
    subtitle: 'Chartered Accountant login',
    email: 'ca@taxvault.demo',
    password: 'Password123!',
    role: 'ca',
    caNumber: 'CA-10001',
    tone: 'slate',
    profile: {
      name: 'Demo CA',
      userType: 'ca',
      taxProfile: null,
      maritalStatus: 'Single',
      spouseInfo: null,
      dependents: [],
    },
  },
];

export const toneMap = {
  blue: {
    bg: '#EFF6FF',
    border: '#BFDBFE',
    title: '#1D4ED8',
    text: '#1E3A8A',
    badgeBg: '#DBEAFE',
  },
  green: {
    bg: '#ECFDF5',
    border: '#A7F3D0',
    title: '#047857',
    text: '#065F46',
    badgeBg: '#D1FAE5',
  },
  amber: {
    bg: '#FFFBEB',
    border: '#FDE68A',
    title: '#B45309',
    text: '#92400E',
    badgeBg: '#FEF3C7',
  },
  purple: {
    bg: '#FAF5FF',
    border: '#D8B4FE',
    title: '#7E22CE',
    text: '#6B21A8',
    badgeBg: '#E9D5FF',
  },
  indigo: {
    bg: '#EEF2FF',
    border: '#C7D2FE',
    title: '#4338CA',
    text: '#3730A3',
    badgeBg: '#E0E7FF',
  },
  teal: {
    bg: '#F0FDFA',
    border: '#99F6E4',
    title: '#0F766E',
    text: '#115E59',
    badgeBg: '#CCFBF1',
  },
  rose: {
    bg: '#FFF1F2',
    border: '#FDA4AF',
    title: '#BE123C',
    text: '#9F1239',
    badgeBg: '#FFE4E6',
  },
  slate: {
    bg: '#F8FAFC',
    border: '#CBD5E1',
    title: '#334155',
    text: '#475569',
    badgeBg: '#E2E8F0',
  },
};
