export const businessChecklist = [
  {
    key: 'businessInfo',
    label: 'Business Info',
    route: 'BusinessInfo',
    icon: 'office-building-outline',
    description: 'Business registration and core profile',
    required: true,
  },
  {
    key: 'salesIncome',
    label: 'Sales Income',
    route: 'BusinessSalesIncome',
    icon: 'cash-multiple',
    description: 'Invoices, revenue, and sales records',
    required: true,
  },
  {
    key: 'expenses',
    label: 'Expenses',
    route: 'BusinessRentUtilities', // you can split later if needed
    icon: 'receipt-outline',
    description: 'Operational expenses and bills',
    required: true,
  },
  {
    key: 'payroll',
    label: 'Payroll',
    route: 'BusinessPayroll',
    icon: 'account-cash-outline',
    description: 'Employee salaries and remittances',
    required: false,
    condition: (profile) => profile?.business?.hasEmployees,
  },
  {
    key: 'gstRecords',
    label: 'GST / HST',
    route: 'BusinessGSTRecords',
    icon: 'receipt-text-check-outline',
    description: 'Tax collected and remitted',
    required: false,
    condition: (profile) => profile?.business?.isGSTRegistered,
  },
  {
    key: 'inventory',
    label: 'Inventory',
    route: 'BusinessInventory',
    icon: 'archive-outline',
    description: 'Stock and cost of goods',
    required: false,
    condition: (profile) => profile?.business?.hasInventory,
  },
  {
    key: 'franchise',
    label: 'Franchise',
    route: 'BusinessFranchise',
    icon: 'file-certificate-outline',
    description: 'Franchise and royalty fees',
    required: false,
    condition: (profile) => profile?.business?.hasFranchise,
  },
  {
    key: 'taxDocuments',
    label: 'Tax Documents',
    route: 'BusinessTaxDocuments',
    icon: 'file-document-multiple-outline',
    description: 'Final reports and tax filings',
    required: true,
  },
];


