import { colors } from '@/styles/theme';

export const BUSINESS_TAX_DOCUMENT_SECTIONS = [
  {
    id: 'business-setup',
    title: 'Business Setup & Legal',
    icon: 'briefcase-check-outline',
    accent: colors.primary[500],
    description:
      'Core business identity and legal documents needed to open the business tax file properly.',
    items: [
      {
        id: 'bn',
        name: 'Business Number (BN)',
        required: true,
        helpText: 'CRA business number / program account details',
        status: 'required',
      },
      {
        id: 'incorporation',
        name: 'Articles of Incorporation / Corporate Setup',
        required: false,
        helpText: 'Needed if the business is incorporated',
        status: 'optional',
      },
      {
        id: 'partnership',
        name: 'Partnership Agreement',
        required: false,
        helpText: 'Needed only for partnerships',
        status: 'optional',
      },
      {
        id: 'license',
        name: 'Business Licence / Municipal Licence',
        required: true,
        helpText: 'Active licence or permit, if applicable',
        status: 'required',
      },
      {
        id: 'prior-year',
        name: 'Prior-Year Tax Return / Notice of Assessment',
        required: true,
        helpText: 'Helps with opening balances, carryforwards, and continuity',
        status: 'required',
      },
    ],
  },
  {
    id: 'sales-income',
    title: 'Sales & Income',
    icon: 'cash-register',
    accent: '#0F9D58',
    description:
      'Income records should support the date, amount, and source of business revenue.',
    items: [
      {
        id: 'sales-summary',
        name: 'Monthly / Annual Sales Summary',
        required: true,
        helpText: 'POS, bookkeeping summary, or spreadsheet',
        status: 'required',
      },
      {
        id: 'sales-invoices',
        name: 'Sales Invoices',
        required: true,
        helpText: 'Invoices issued to customers',
        status: 'required',
      },
      {
        id: 'processor',
        name: 'Merchant Processor Statements',
        required: true,
        helpText: 'Square, Stripe, Moneris, Lightspeed, etc.',
        status: 'required',
      },
      {
        id: 'deposits',
        name: 'Bank Deposit Slips / Deposit Support',
        required: true,
        helpText: 'Useful to reconcile revenue to bank',
        status: 'required',
      },
      {
        id: 'contracts',
        name: 'Service Contracts / Client Agreements',
        required: false,
        helpText: 'Helpful for contract revenue and large projects',
        status: 'optional',
      },
      {
        id: 'other-income',
        name: 'Other Income Support',
        required: false,
        helpText: 'Commissions, rebates, incentives, miscellaneous income',
        status: 'optional',
      },
    ],
  },
  {
    id: 'expenses',
    title: 'Expenses & Operating Costs',
    icon: 'receipt-text-check-outline',
    accent: '#F59E0B',
    description:
      'Upload supporting receipts, bills, and vouchers for ordinary business expenses.',
    items: [
      {
        id: 'rent',
        name: 'Rent Receipts / Monthly Rent Statements',
        required: true,
        helpText: 'Include lease-backed rent payments',
        status: 'required',
      },
      {
        id: 'utilities',
        name: 'Utilities Bills',
        required: true,
        helpText: 'Electricity, gas, water, waste, internet, phone',
        status: 'required',
      },
      {
        id: 'supplies',
        name: 'Office / Store Supplies',
        required: true,
        helpText: 'Consumables, stationery, packaging, cleaning supplies',
        status: 'required',
      },
      {
        id: 'repairs',
        name: 'Repairs & Maintenance',
        required: false,
        helpText: 'Store repairs, equipment maintenance',
        status: 'optional',
      },
      {
        id: 'advertising',
        name: 'Advertising & Marketing',
        required: false,
        helpText: 'Ads, flyers, digital spend, promotions',
        status: 'optional',
      },
      {
        id: 'professional-fees',
        name: 'Professional Fees',
        required: false,
        helpText: 'Accounting, legal, consulting',
        status: 'optional',
      },
      {
        id: 'bank-charges',
        name: 'Bank Charges & Interest',
        required: false,
        helpText: 'Bank fees, loan interest, card processing fees',
        status: 'optional',
      },
      {
        id: 'travel-meals',
        name: 'Business Travel / Meals Support',
        required: false,
        helpText: 'Only the business portion with purpose noted',
        status: 'optional',
      },
    ],
  },
  {
    id: 'payroll',
    title: 'Payroll & Employees',
    icon: 'account-group-outline',
    accent: '#3B82F6',
    description:
      'Needed if the business pays wages, salary, commissions, or contractor amounts.',
    items: [
      {
        id: 'payroll-register',
        name: 'Payroll Register / Payroll Summary',
        required: true,
        helpText: 'Employee-by-employee payroll detail',
        status: 'required',
      },
      {
        id: 'hours-worked',
        name: 'Hours Worked Records',
        required: true,
        helpText: 'CRA payroll records should include hours worked',
        status: 'required',
      },
      {
        id: 'td1',
        name: 'Employee TD1 Forms',
        required: true,
        helpText: 'Federal TD1 for employees',
        status: 'required',
      },
      {
        id: 't4-t4a',
        name: 'T4 / T4A Slips and Summaries',
        required: true,
        helpText: 'Year-end payroll or contractor reporting support',
        status: 'required',
      },
      {
        id: 'remittances',
        name: 'CPP / EI / Tax Remittance Confirmations',
        required: true,
        helpText: 'Proof of payroll remittances to CRA',
        status: 'required',
      },
      {
        id: 'pension',
        name: 'Registered Pension Information',
        required: false,
        helpText: 'Only if applicable',
        status: 'optional',
      },
    ],
  },
  {
    id: 'gst-hst',
    title: 'GST/HST',
    icon: 'percent-circle-outline',
    accent: '#8B5CF6',
    description:
      'Needed to support tax collected, tax paid, and input tax credit claims.',
    items: [
      {
        id: 'gst-returns',
        name: 'GST/HST Returns Filed',
        required: true,
        helpText: 'Filed returns and filing confirmations',
        status: 'required',
      },
      {
        id: 'tax-collected',
        name: 'Sales Tax Collected Summary',
        required: true,
        helpText: 'Sales reports showing GST/HST charged',
        status: 'required',
      },
      {
        id: 'itc-support',
        name: 'Purchase Invoices for ITCs',
        required: true,
        helpText: 'Receipts/invoices supporting input tax credits',
        status: 'required',
      },
      {
        id: 'gst-workpapers',
        name: 'GST/HST Reconciliation Workpapers',
        required: false,
        helpText: 'Helpful when books and filed returns differ',
        status: 'optional',
      },
    ],
  },
  {
    id: 'inventory',
    title: 'Inventory & Cost of Goods Sold',
    icon: 'package-variant-closed',
    accent: '#EF4444',
    description:
      'Important for retailers, product businesses, convenience stores, and franchises.',
    items: [
      {
        id: 'opening-inventory',
        name: 'Opening Inventory',
        required: true,
        helpText: 'Inventory at the start of the year',
        status: 'required',
      },
      {
        id: 'closing-inventory',
        name: 'Closing Inventory',
        required: true,
        helpText: 'Inventory count at year-end',
        status: 'required',
      },
      {
        id: 'supplier-invoices',
        name: 'Supplier Purchase Invoices',
        required: true,
        helpText: 'Inventory and stock purchases',
        status: 'required',
      },
      {
        id: 'inventory-adjustments',
        name: 'Shrinkage / Write-off / Adjustment Notes',
        required: false,
        helpText: 'Damaged goods, spoilage, loss adjustments',
        status: 'optional',
      },
    ],
  },
  {
    id: 'insurance',
    title: 'Insurance',
    icon: 'shield-check-outline',
    accent: '#14B8A6',
    description:
      'Commercial insurance supports deductible business insurance expense claims.',
    items: [
      {
        id: 'policy',
        name: 'Commercial Insurance Policy',
        required: false,
        helpText: 'Business liability, contents, property, vehicle, etc.',
        status: 'optional',
      },
      {
        id: 'premium-invoices',
        name: 'Insurance Premium Invoices',
        required: false,
        helpText: 'Billing statements and renewal notices',
        status: 'optional',
      },
      {
        id: 'payment-proof',
        name: 'Payment Confirmations',
        required: false,
        helpText: 'Proof premiums were paid',
        status: 'optional',
      },
    ],
  },
  {
    id: 'franchise',
    title: 'Franchise Fees & Royalties',
    icon: 'file-document-multiple-outline',
    accent: '#F97316',
    description:
      'For franchise-based businesses with royalties, marketing funds, or franchise charges.',
    items: [
      {
        id: 'franchise-agreement',
        name: 'Franchise Agreement',
        required: false,
        helpText: 'Master agreement with franchisor',
        status: 'optional',
      },
      {
        id: 'royalty-statements',
        name: 'Royalty Statements',
        required: false,
        helpText: 'Periodic royalty and brand fees',
        status: 'optional',
      },
      {
        id: 'marketing-fund',
        name: 'Marketing / System Fee Charges',
        required: false,
        helpText: 'Ad fund or franchisor support fees',
        status: 'optional',
      },
    ],
  },
  {
    id: 'lease-property',
    title: 'Lease & Property',
    icon: 'home-city-outline',
    accent: '#6366F1',
    description:
      'Important where the business operates from leased retail or office premises.',
    items: [
      {
        id: 'lease-agreement',
        name: 'Lease Agreement',
        required: true,
        helpText: 'Base rent, additional rent, and term details',
        status: 'required',
      },
      {
        id: 'cam-charges',
        name: 'Additional Rent / CAM / Property Charges',
        required: false,
        helpText: 'Common area maintenance, operating cost allocations',
        status: 'optional',
      },
      {
        id: 'property-tax',
        name: 'Property Tax Bills',
        required: false,
        helpText: 'If property is owned instead of leased',
        status: 'optional',
      },
    ],
  },
  {
    id: 'assets',
    title: 'Equipment, Vehicles & Capital Assets',
    icon: 'laptop-account',
    accent: '#0EA5E9',
    description:
      'Capital purchases are usually tracked separately for CCA rather than expensed immediately.',
    items: [
      {
        id: 'equipment-purchases',
        name: 'Equipment / Furniture Purchase Invoices',
        required: false,
        helpText: 'Computers, counters, shelving, machinery, furniture',
        status: 'optional',
      },
      {
        id: 'vehicle-purchases',
        name: 'Vehicle Purchase / Financing Documents',
        required: false,
        helpText: 'If used in the business',
        status: 'optional',
      },
      {
        id: 'loan-docs',
        name: 'Loan / Financing Agreements',
        required: false,
        helpText: 'Useful for interest and asset continuity',
        status: 'optional',
      },
      {
        id: 'asset-disposals',
        name: 'Asset Sale / Disposal Support',
        required: false,
        helpText: 'Needed if assets were sold or scrapped',
        status: 'optional',
      },
    ],
  },
  {
    id: 'banking',
    title: 'Banking & Reconciliation',
    icon: 'bank-outline',
    accent: '#475569',
    description:
      'Helps the CA reconcile sales, expenses, payroll, and transfers properly.',
    items: [
      {
        id: 'bank-statements',
        name: 'Business Bank Statements',
        required: true,
        helpText: 'All accounts used by the business',
        status: 'required',
      },
      {
        id: 'credit-card-statements',
        name: 'Business Credit Card Statements',
        required: true,
        helpText: 'Support expense transactions',
        status: 'required',
      },
      {
        id: 'loan-statements',
        name: 'Loan Statements',
        required: false,
        helpText: 'For principal/interest split and continuity',
        status: 'optional',
      },
      {
        id: 'bookkeeping-export',
        name: 'Bookkeeping Export / Trial Balance / P&L',
        required: true,
        helpText: 'QuickBooks, Xero, Excel, or accountant working papers',
        status: 'required',
      },
    ],
  },
];

export const BUSINESS_FILING_NOTES = [
  'Most raw supporting documents are uploaded for the accountant and retained for CRA review if requested later.',
  'For sole proprietors/partnerships, these documents support Form T2125 business income and expense reporting.',
  'For corporations, the T2 filing usually requires financial statements or GIFI plus the required schedules.',
  'Keep records organized by tax year and category to make review, GST/HST reconciliation, and payroll checks easier.',
];


