export const caStats = {
  totalClients: 14,
  activeClients: 9,
  pendingRequests: 5,
  unreadMessages: 18,
  documentsToReview: 13,
  todayMeetings: 6,
  households: 6,
  singles: 8,
};

export const caClients = [
  // =========================
  // SINGLE USERS
  // =========================

  {
    id: 'client-001',
    clientCode: 'TVC-2026-1001',
    name: 'Rahul Verma',
    accountType: 'single',
    province: 'AB',
    city: 'Fort McMurray',
    taxYear: 2025,
    status: 'ready_to_file',
    checklistProgress: 96,
    unreadMessages: 0,
    pendingRequests: 0,
    nextMeeting: 'No meeting scheduled',
    missingDocs: 0,
    hasSpouse: false,
    hasAssignedCA: true,
    assignedCA: {
      id: 'ca-001',
      name: 'Amanpreet Sandhu, CPA',
      firmName: 'Northern Tax Partners',
      rating: 4.9,
    },
    members: {
      primary: 'Rahul Verma',
      spouse: null,
    },
    incomeProfile: {
      primary: ['Employment'],
      spouse: [],
    },
    documentsState: {
      t4: true,
      t4a: false,
      businessDocs: false,
      investmentDocs: false,
      rrsp: false,
      fhsa: false,
      receipts: false,
      mileage: false,
    },
  },

  {
    id: 'client-002',
    clientCode: 'TVC-2026-1002',
    name: 'Simran Kaur',
    accountType: 'single',
    province: 'AB',
    city: 'Edmonton',
    taxYear: 2025,
    status: 'awaiting_documents',
    checklistProgress: 41,
    unreadMessages: 2,
    pendingRequests: 1,
    nextMeeting: 'Today, 4:00 PM',
    missingDocs: 5,
    hasSpouse: false,
    hasAssignedCA: false,
    assignedCA: null,
    members: {
      primary: 'Simran Kaur',
      spouse: null,
    },
    incomeProfile: {
      primary: ['Gig Work'],
      spouse: [],
    },
    documentsState: {
      t4: false,
      t4a: true,
      businessDocs: false,
      investmentDocs: false,
      rrsp: false,
      fhsa: false,
      receipts: true,
      mileage: true,
    },
  },

  {
    id: 'client-003',
    clientCode: 'TVC-2026-1003',
    name: 'Priya Patel',
    accountType: 'single',
    province: 'AB',
    city: 'Edmonton',
    taxYear: 2025,
    status: 'review_in_progress',
    checklistProgress: 84,
    unreadMessages: 1,
    pendingRequests: 0,
    nextMeeting: 'Tomorrow, 2:00 PM',
    missingDocs: 1,
    hasSpouse: false,
    hasAssignedCA: true,
    assignedCA: {
      id: 'ca-002',
      name: 'Jasleen Brar, CPA',
      firmName: 'Prairie Ledger Tax',
      rating: 4.8,
    },
    members: {
      primary: 'Priya Patel',
      spouse: null,
    },
    incomeProfile: {
      primary: ['Business'],
      spouse: [],
    },
    documentsState: {
      t4: false,
      t4a: false,
      businessDocs: true,
      investmentDocs: false,
      rrsp: false,
      fhsa: false,
      receipts: true,
      mileage: false,
    },
  },

  {
    id: 'client-004',
    clientCode: 'TVC-2026-1004',
    name: 'Harleen Kaur',
    accountType: 'single',
    province: 'BC',
    city: 'Surrey',
    taxYear: 2025,
    status: 'documents_received',
    checklistProgress: 77,
    unreadMessages: 2,
    pendingRequests: 0,
    nextMeeting: 'Friday, 11:00 AM',
    missingDocs: 2,
    hasSpouse: false,
    hasAssignedCA: true,
    assignedCA: {
      id: 'ca-003',
      name: 'Ritika Saini, CPA',
      firmName: 'WestEdge Tax Studio',
      rating: 4.7,
    },
    members: {
      primary: 'Harleen Kaur',
      spouse: null,
    },
    incomeProfile: {
      primary: ['Employment', 'Investments'],
      spouse: [],
    },
    documentsState: {
      t4: true,
      t4a: false,
      businessDocs: false,
      investmentDocs: true,
      rrsp: true,
      fhsa: false,
      receipts: false,
      mileage: false,
    },
  },

  {
    id: 'client-005',
    clientCode: 'TVC-2026-1005',
    name: 'Aakash Sharma',
    accountType: 'single',
    province: 'ON',
    city: 'Toronto',
    taxYear: 2025,
    status: 'awaiting_documents',
    checklistProgress: 52,
    unreadMessages: 3,
    pendingRequests: 1,
    nextMeeting: 'Thursday, 9:30 AM',
    missingDocs: 4,
    hasSpouse: false,
    hasAssignedCA: false,
    assignedCA: null,
    members: {
      primary: 'Aakash Sharma',
      spouse: null,
    },
    incomeProfile: {
      primary: ['Employment', 'Gig Work'],
      spouse: [],
    },
    documentsState: {
      t4: true,
      t4a: true,
      businessDocs: false,
      investmentDocs: false,
      rrsp: false,
      fhsa: false,
      receipts: true,
      mileage: true,
    },
  },

  {
    id: 'client-006',
    clientCode: 'TVC-2026-1006',
    name: 'Nisha Bedi',
    accountType: 'single',
    province: 'BC',
    city: 'Burnaby',
    taxYear: 2025,
    status: 'consultation_requested',
    checklistProgress: 38,
    unreadMessages: 1,
    pendingRequests: 1,
    nextMeeting: 'Pending approval',
    missingDocs: 5,
    hasSpouse: false,
    hasAssignedCA: false,
    assignedCA: null,
    members: {
      primary: 'Nisha Bedi',
      spouse: null,
    },
    incomeProfile: {
      primary: ['Employment', 'Business'],
      spouse: [],
    },
    documentsState: {
      t4: true,
      t4a: false,
      businessDocs: true,
      investmentDocs: false,
      rrsp: false,
      fhsa: false,
      receipts: true,
      mileage: false,
    },
  },

  {
    id: 'client-007',
    clientCode: 'TVC-2026-1007',
    name: 'Karan Gill',
    accountType: 'single',
    province: 'AB',
    city: 'Calgary',
    taxYear: 2025,
    status: 'documents_received',
    checklistProgress: 72,
    unreadMessages: 2,
    pendingRequests: 0,
    nextMeeting: 'Monday, 1:00 PM',
    missingDocs: 2,
    hasSpouse: false,
    hasAssignedCA: true,
    assignedCA: {
      id: 'ca-001',
      name: 'Amanpreet Sandhu, CPA',
      firmName: 'Northern Tax Partners',
      rating: 4.9,
    },
    members: {
      primary: 'Karan Gill',
      spouse: null,
    },
    incomeProfile: {
      primary: ['Gig Work', 'Business'],
      spouse: [],
    },
    documentsState: {
      t4: false,
      t4a: true,
      businessDocs: true,
      investmentDocs: false,
      rrsp: false,
      fhsa: false,
      receipts: true,
      mileage: true,
    },
  },

  {
    id: 'client-008',
    clientCode: 'TVC-2026-1008',
    name: 'Mehak Arora',
    accountType: 'single',
    province: 'ON',
    city: 'Brampton',
    taxYear: 2025,
    status: 'awaiting_documents',
    checklistProgress: 61,
    unreadMessages: 4,
    pendingRequests: 1,
    nextMeeting: 'Saturday, 12:30 PM',
    missingDocs: 3,
    hasSpouse: false,
    hasAssignedCA: true,
    assignedCA: {
      id: 'ca-004',
      name: 'Navdeep Chahal, CPA',
      firmName: 'Maple Filing Co.',
      rating: 4.6,
    },
    members: {
      primary: 'Mehak Arora',
      spouse: null,
    },
    incomeProfile: {
      primary: ['Employment', 'Gig Work', 'Business'],
      spouse: [],
    },
    documentsState: {
      t4: true,
      t4a: true,
      businessDocs: true,
      investmentDocs: false,
      rrsp: true,
      fhsa: false,
      receipts: true,
      mileage: true,
    },
  },

  // =========================
  // HOUSEHOLD USERS
  // =========================

  {
    id: 'client-009',
    clientCode: 'TVC-2026-1009',
    name: 'Aman & Neha Sharma',
    accountType: 'household',
    province: 'AB',
    city: 'Calgary',
    taxYear: 2025,
    status: 'awaiting_documents',
    checklistProgress: 68,
    unreadMessages: 3,
    pendingRequests: 1,
    nextMeeting: 'Today, 10:30 AM',
    missingDocs: 4,
    hasSpouse: true,
    hasAssignedCA: true,
    assignedCA: {
      id: 'ca-001',
      name: 'Amanpreet Sandhu, CPA',
      firmName: 'Northern Tax Partners',
      rating: 4.9,
    },
    members: {
      primary: 'Aman Sharma',
      spouse: 'Neha Sharma',
    },
    incomeProfile: {
      primary: ['Employment', 'Gig Work'],
      spouse: ['Employment'],
    },
    documentsState: {
      t4: true,
      t4a: true,
      businessDocs: false,
      investmentDocs: false,
      rrsp: true,
      fhsa: false,
      receipts: true,
      mileage: true,
    },
  },

  {
    id: 'client-010',
    clientCode: 'TVC-2026-1010',
    name: 'Neha & Karan Singh',
    accountType: 'household',
    province: 'ON',
    city: 'Mississauga',
    taxYear: 2025,
    status: 'consultation_requested',
    checklistProgress: 24,
    unreadMessages: 5,
    pendingRequests: 1,
    nextMeeting: 'Pending approval',
    missingDocs: 6,
    hasSpouse: true,
    hasAssignedCA: false,
    assignedCA: null,
    members: {
      primary: 'Neha Singh',
      spouse: 'Karan Singh',
    },
    incomeProfile: {
      primary: ['Employment'],
      spouse: ['Business'],
    },
    documentsState: {
      t4: true,
      t4a: false,
      businessDocs: true,
      investmentDocs: false,
      rrsp: false,
      fhsa: false,
      receipts: true,
      mileage: false,
    },
  },

  {
    id: 'client-011',
    clientCode: 'TVC-2026-1011',
    name: 'Rohit & Mehak',
    accountType: 'household',
    province: 'ON',
    city: 'Milton',
    taxYear: 2025,
    status: 'documents_received',
    checklistProgress: 73,
    unreadMessages: 2,
    pendingRequests: 0,
    nextMeeting: 'Tomorrow, 11:00 AM',
    missingDocs: 2,
    hasSpouse: true,
    hasAssignedCA: true,
    assignedCA: {
      id: 'ca-002',
      name: 'Jasleen Brar, CPA',
      firmName: 'Prairie Ledger Tax',
      rating: 4.8,
    },
    members: {
      primary: 'Rohit Mehra',
      spouse: 'Mehak Mehra',
    },
    incomeProfile: {
      primary: ['Employment'],
      spouse: ['Investments'],
    },
    documentsState: {
      t4: true,
      t4a: false,
      businessDocs: false,
      investmentDocs: true,
      rrsp: true,
      fhsa: false,
      receipts: false,
      mileage: false,
    },
  },

  {
    id: 'client-012',
    clientCode: 'TVC-2026-1012',
    name: 'Vikas & Pooja Arora',
    accountType: 'household',
    province: 'BC',
    city: 'Vancouver',
    taxYear: 2025,
    status: 'review_in_progress',
    checklistProgress: 81,
    unreadMessages: 1,
    pendingRequests: 0,
    nextMeeting: 'Friday, 1:30 PM',
    missingDocs: 1,
    hasSpouse: true,
    hasAssignedCA: true,
    assignedCA: {
      id: 'ca-003',
      name: 'Ritika Saini, CPA',
      firmName: 'WestEdge Tax Studio',
      rating: 4.7,
    },
    members: {
      primary: 'Vikas Arora',
      spouse: 'Pooja Arora',
    },
    incomeProfile: {
      primary: ['Business'],
      spouse: ['Employment'],
    },
    documentsState: {
      t4: true,
      t4a: false,
      businessDocs: true,
      investmentDocs: false,
      rrsp: false,
      fhsa: false,
      receipts: true,
      mileage: false,
    },
  },

  {
    id: 'client-013',
    clientCode: 'TVC-2026-1013',
    name: 'Sandeep & Jaspreet Dhillon',
    accountType: 'household',
    province: 'AB',
    city: 'Red Deer',
    taxYear: 2025,
    status: 'awaiting_documents',
    checklistProgress: 49,
    unreadMessages: 3,
    pendingRequests: 1,
    nextMeeting: 'Monday, 3:00 PM',
    missingDocs: 5,
    hasSpouse: true,
    hasAssignedCA: false,
    assignedCA: null,
    members: {
      primary: 'Sandeep Dhillon',
      spouse: 'Jaspreet Dhillon',
    },
    incomeProfile: {
      primary: ['Gig Work'],
      spouse: ['Gig Work'],
    },
    documentsState: {
      t4: false,
      t4a: true,
      businessDocs: false,
      investmentDocs: false,
      rrsp: false,
      fhsa: false,
      receipts: true,
      mileage: true,
    },
  },

  {
    id: 'client-014',
    clientCode: 'TVC-2026-1014',
    name: 'Manpreet & Aditi Bains',
    accountType: 'household',
    province: 'ON',
    city: 'Ottawa',
    taxYear: 2025,
    status: 'consultation_requested',
    checklistProgress: 33,
    unreadMessages: 4,
    pendingRequests: 1,
    nextMeeting: 'Pending approval',
    missingDocs: 6,
    hasSpouse: true,
    hasAssignedCA: true,
    assignedCA: {
      id: 'ca-004',
      name: 'Navdeep Chahal, CPA',
      firmName: 'Maple Filing Co.',
      rating: 4.6,
    },
    members: {
      primary: 'Manpreet Bains',
      spouse: 'Aditi Bains',
    },
    incomeProfile: {
      primary: ['Employment', 'Business'],
      spouse: ['Employment', 'Gig Work'],
    },
    documentsState: {
      t4: true,
      t4a: true,
      businessDocs: true,
      investmentDocs: false,
      rrsp: true,
      fhsa: true,
      receipts: true,
      mileage: true,
    },
  },
];

export const caRequests = [
  {
    id: 'request-001',
    name: 'Ishita Malhotra',
    accountType: 'single',
    province: 'AB',
    consultationType: 'New Tax Filing',
    preferredTime: 'Today, 4:00 PM',
    status: 'pending',
    note: 'Need help with self-employed tax filing and expense tracking for 2025.',
    incomeTags: ['Gig Work'],
    docsUploaded: 3,
    hasAssignedCA: false,
  },
  {
    id: 'request-002',
    name: 'Rohit & Kavya',
    accountType: 'household',
    province: 'ON',
    consultationType: 'Tax Planning Consultation',
    preferredTime: 'Tomorrow, 11:00 AM',
    status: 'pending',
    note: 'Household filing with RRSP and investment income. Need guidance on deductions.',
    incomeTags: ['Employment', 'Investments'],
    docsUploaded: 5,
    hasAssignedCA: false,
  },
  {
    id: 'request-003',
    name: 'Vikram Sethi',
    accountType: 'single',
    province: 'BC',
    consultationType: 'Business Return Guidance',
    preferredTime: 'Friday, 1:30 PM',
    status: 'pending',
    note: 'Need help organizing business records and understanding eligible write-offs.',
    incomeTags: ['Business'],
    docsUploaded: 2,
    hasAssignedCA: false,
  },
  {
    id: 'request-004',
    name: 'Puneet & Ria',
    accountType: 'household',
    province: 'AB',
    consultationType: 'Joint Return Setup',
    preferredTime: 'Saturday, 10:00 AM',
    status: 'pending',
    note: 'Primary has T4, spouse has gig income and receipts.',
    incomeTags: ['Employment', 'Gig Work'],
    docsUploaded: 4,
    hasAssignedCA: false,
  },
  {
    id: 'request-005',
    name: 'Dev Khanna',
    accountType: 'single',
    province: 'ON',
    consultationType: 'CA Matching',
    preferredTime: 'Monday, 12:00 PM',
    status: 'pending',
    note: 'Needs a CA for employment + business filing.',
    incomeTags: ['Employment', 'Business'],
    docsUploaded: 1,
    hasAssignedCA: false,
  },
];

export const caMessages = [
  {
    id: 'msg-001',
    clientName: 'Aman & Neha Sharma',
    accountType: 'household',
    lastMessage:
      'I uploaded the fuel and maintenance receipts. Please review when you get a chance.',
    time: '9:12 AM',
    unreadCount: 2,
    priority: 'high',
    taxYear: 2025,
    hasAssignedCA: true,
  },
  {
    id: 'msg-002',
    clientName: 'Priya Patel',
    accountType: 'single',
    lastMessage: 'Can we move the consultation to tomorrow afternoon instead?',
    time: 'Yesterday',
    unreadCount: 1,
    priority: 'medium',
    taxYear: 2025,
    hasAssignedCA: true,
  },
  {
    id: 'msg-003',
    clientName: 'Rahul Verma',
    accountType: 'single',
    lastMessage: 'Thanks, everything looks good from my side.',
    time: 'Yesterday',
    unreadCount: 0,
    priority: 'low',
    taxYear: 2025,
    hasAssignedCA: true,
  },
  {
    id: 'msg-004',
    clientName: 'Neha & Karan Singh',
    accountType: 'household',
    lastMessage: 'We want to book a call this week for our joint return.',
    time: 'Monday',
    unreadCount: 4,
    priority: 'high',
    taxYear: 2025,
    hasAssignedCA: false,
  },
  {
    id: 'msg-005',
    clientName: 'Mehak Arora',
    accountType: 'single',
    lastMessage: 'I still need to upload one business statement and my RRSP slip.',
    time: 'Monday',
    unreadCount: 3,
    priority: 'medium',
    taxYear: 2025,
    hasAssignedCA: true,
  },
];

export const caPlannerTasks = [
  {
    id: 'task-001',
    title: 'Review uploaded receipts',
    subtitle: 'Aman & Neha Sharma',
    time: '10:00 AM',
    type: 'review',
    status: 'pending',
  },
  {
    id: 'task-002',
    title: 'Consultation call',
    subtitle: 'Ishita Malhotra',
    time: '11:30 AM',
    type: 'meeting',
    status: 'scheduled',
  },
  {
    id: 'task-003',
    title: 'Follow up on missing T4',
    subtitle: 'Neha & Karan Singh',
    time: '1:00 PM',
    type: 'follow_up',
    status: 'pending',
  },
  {
    id: 'task-004',
    title: 'Final review before filing',
    subtitle: 'Priya Patel',
    time: '3:30 PM',
    type: 'filing',
    status: 'scheduled',
  },
  {
    id: 'task-005',
    title: 'Approve consultation request',
    subtitle: 'Rohit & Kavya',
    time: '5:00 PM',
    type: 'approval',
    status: 'pending',
  },
  {
    id: 'task-006',
    title: 'Assign CA to new lead',
    subtitle: 'Dev Khanna',
    time: '6:00 PM',
    type: 'assignment',
    status: 'pending',
  },
];

export const caMeetings = [
  {
    id: 'meeting-001',
    clientName: 'Aman & Neha Sharma',
    accountType: 'household',
    type: 'Consultation',
    date: '2026-03-24',
    time: '10:30 AM',
    status: 'accepted',
    mode: 'Video Call',
    hasAssignedCA: true,
  },
  {
    id: 'meeting-002',
    clientName: 'Ishita Malhotra',
    accountType: 'single',
    type: 'New Client Intake',
    date: '2026-03-24',
    time: '11:30 AM',
    status: 'pending',
    mode: 'Phone Call',
    hasAssignedCA: false,
  },
  {
    id: 'meeting-003',
    clientName: 'Priya Patel',
    accountType: 'single',
    type: 'Return Review',
    date: '2026-03-25',
    time: '2:00 PM',
    status: 'accepted',
    mode: 'Video Call',
    hasAssignedCA: true,
  },
  {
    id: 'meeting-004',
    clientName: 'Neha & Karan Singh',
    accountType: 'household',
    type: 'Household Filing Consultation',
    date: '2026-03-26',
    time: '1:00 PM',
    status: 'pending',
    mode: 'In App Meeting',
    hasAssignedCA: false,
  },
  {
    id: 'meeting-005',
    clientName: 'Mehak Arora',
    accountType: 'single',
    type: 'Business + T4 Review',
    date: '2026-03-27',
    time: '9:30 AM',
    status: 'accepted',
    mode: 'Video Call',
    hasAssignedCA: true,
  },
  {
    id: 'meeting-006',
    clientName: 'Manpreet & Aditi Bains',
    accountType: 'household',
    type: 'Joint Return Planning',
    date: '2026-03-28',
    time: '4:00 PM',
    status: 'accepted',
    mode: 'In App Meeting',
    hasAssignedCA: true,
  },
];


