export const caStats = {
  totalClients: 42,
  activeClients: 42,
  pendingRequests: 8,
  unreadMessages: 14,
  documentsToReview: 11,
  todayMeetings: 5,
  households: 16,
  singles: 26,
};

export const caClients = [
  {
    id: 'client-001',
    clientCode: 'TVC-2026-1001',
    name: 'Aman Sharma',
    accountType: 'household',
    province: 'AB',
    city: 'Calgary',
    taxYear: 2025,
    status: 'awaiting_documents',
    checklistProgress: 68,
    unreadMessages: 3,
    pendingRequests: 1,
    nextMeeting: 'Today, 10:30 AM',
    missingDocs: 4,
    members: {
      primary: 'Aman Sharma',
      spouse: 'Neha Sharma',
    },
    incomeProfile: {
      primary: ['Employment', 'Gig Work'],
      spouse: ['Employment'],
    },
  },
  {
    id: 'client-002',
    clientCode: 'TVC-2026-1002',
    name: 'Priya Patel',
    accountType: 'single',
    province: 'AB',
    city: 'Edmonton',
    taxYear: 2025,
    status: 'review_in_progress',
    checklistProgress: 84,
    unreadMessages: 1,
    pendingRequests: 0,
    nextMeeting: 'Tomorrow, 2:00 PM',
    missingDocs: 1,
    members: {
      primary: 'Priya Patel',
      spouse: null,
    },
    incomeProfile: {
      primary: ['Business'],
      spouse: [],
    },
  },
  {
    id: 'client-003',
    clientCode: 'TVC-2026-1003',
    name: 'Rahul Verma',
    accountType: 'single',
    province: 'AB',
    city: 'Fort McMurray',
    taxYear: 2025,
    status: 'ready_to_file',
    checklistProgress: 96,
    unreadMessages: 0,
    pendingRequests: 0,
    nextMeeting: 'No meeting scheduled',
    missingDocs: 0,
    members: {
      primary: 'Rahul Verma',
      spouse: null,
    },
    incomeProfile: {
      primary: ['Employment'],
      spouse: [],
    },
  },
  {
    id: 'client-004',
    clientCode: 'TVC-2026-1004',
    name: 'Neha & Karan Singh',
    accountType: 'household',
    province: 'ON',
    city: 'Mississauga',
    taxYear: 2025,
    status: 'consultation_requested',
    checklistProgress: 24,
    unreadMessages: 5,
    pendingRequests: 1,
    nextMeeting: 'Pending approval',
    missingDocs: 6,
    members: {
      primary: 'Neha Singh',
      spouse: 'Karan Singh',
    },
    incomeProfile: {
      primary: ['Employment'],
      spouse: ['Business'],
    },
  },
  {
    id: 'client-005',
    clientCode: 'TVC-2026-1005',
    name: 'Harleen Kaur',
    accountType: 'single',
    province: 'BC',
    city: 'Surrey',
    taxYear: 2025,
    status: 'documents_received',
    checklistProgress: 77,
    unreadMessages: 2,
    pendingRequests: 0,
    nextMeeting: 'Friday, 11:00 AM',
    missingDocs: 2,
    members: {
      primary: 'Harleen Kaur',
      spouse: null,
    },
    incomeProfile: {
      primary: ['Employment', 'Investments'],
      spouse: [],
    },
  },
];

export const caRequests = [
  {
    id: 'request-001',
    name: 'Simran Kaur',
    accountType: 'single',
    province: 'AB',
    consultationType: 'New Tax Filing',
    preferredTime: 'Today, 4:00 PM',
    status: 'pending',
    note: 'Need help with self-employed tax filing and expense tracking for 2025.',
    incomeTags: ['Gig Work'],
    docsUploaded: 3,
  },
  {
    id: 'request-002',
    name: 'Rohit & Mehak',
    accountType: 'household',
    province: 'ON',
    consultationType: 'Tax Planning Consultation',
    preferredTime: 'Tomorrow, 11:00 AM',
    status: 'pending',
    note: 'Household filing with RRSP and investment income. Need guidance on deductions.',
    incomeTags: ['Employment', 'Investments'],
    docsUploaded: 5,
  },
  {
    id: 'request-003',
    name: 'Vikas Arora',
    accountType: 'single',
    province: 'BC',
    consultationType: 'Business Return Guidance',
    preferredTime: 'Friday, 1:30 PM',
    status: 'pending',
    note: 'Need help organizing business records and understanding eligible write-offs.',
    incomeTags: ['Business'],
    docsUploaded: 2,
  },
];

export const caMessages = [
  {
    id: 'msg-001',
    clientName: 'Aman Sharma',
    accountType: 'household',
    lastMessage:
      'I uploaded the fuel and maintenance receipts. Please review when you get a chance.',
    time: '9:12 AM',
    unreadCount: 2,
    priority: 'high',
    taxYear: 2025,
  },
  {
    id: 'msg-002',
    clientName: 'Priya Patel',
    accountType: 'single',
    lastMessage: 'Can we move the consultation to tomorrow afternoon instead?',
    time: 'Yesterday',
    unreadCount: 1,
    priority: 'medium',
    taxYear: 2025,
  },
  {
    id: 'msg-003',
    clientName: 'Rahul Verma',
    accountType: 'single',
    lastMessage: 'Thanks, everything looks good from my side.',
    time: 'Yesterday',
    unreadCount: 0,
    priority: 'low',
    taxYear: 2025,
  },
  {
    id: 'msg-004',
    clientName: 'Neha & Karan Singh',
    accountType: 'household',
    lastMessage: 'We want to book a call this week for our joint return.',
    time: 'Monday',
    unreadCount: 4,
    priority: 'high',
    taxYear: 2025,
  },
];

export const caPlannerTasks = [
  {
    id: 'task-001',
    title: 'Review uploaded receipts',
    subtitle: 'Aman Sharma',
    time: '10:00 AM',
    type: 'review',
    status: 'pending',
  },
  {
    id: 'task-002',
    title: 'Consultation call',
    subtitle: 'Simran Kaur',
    time: '11:30 AM',
    type: 'meeting',
    status: 'scheduled',
  },
  {
    id: 'task-003',
    title: 'Follow up on missing T4',
    subtitle: 'Neha & Karan Singh',
    time: '1:00 PM',
    type: 'follow_up',
    status: 'pending',
  },
  {
    id: 'task-004',
    title: 'Final review before filing',
    subtitle: 'Priya Patel',
    time: '3:30 PM',
    type: 'filing',
    status: 'scheduled',
  },
  {
    id: 'task-005',
    title: 'Approve consultation request',
    subtitle: 'Rohit & Mehak',
    time: '5:00 PM',
    type: 'approval',
    status: 'pending',
  },
];

export const caMeetings = [
  {
    id: 'meeting-001',
    clientName: 'Aman Sharma',
    accountType: 'household',
    type: 'Consultation',
    date: '2026-03-24',
    time: '10:30 AM',
    status: 'accepted',
    mode: 'Video Call',
  },
  {
    id: 'meeting-002',
    clientName: 'Simran Kaur',
    accountType: 'single',
    type: 'New Client Intake',
    date: '2026-03-24',
    time: '11:30 AM',
    status: 'pending',
    mode: 'Phone Call',
  },
  {
    id: 'meeting-003',
    clientName: 'Priya Patel',
    accountType: 'single',
    type: 'Return Review',
    date: '2026-03-25',
    time: '2:00 PM',
    status: 'accepted',
    mode: 'Video Call',
  },
  {
    id: 'meeting-004',
    clientName: 'Neha & Karan Singh',
    accountType: 'household',
    type: 'Household Filing Consultation',
    date: '2026-03-26',
    time: '1:00 PM',
    status: 'pending',
    mode: 'In App Meeting',
  },
];