export const CA_SPECIALTIES = [
  'Personal Tax',
  'Self-Employed',
  'Gig Workers',
  'Small Business',
  'Corporate Tax',
  'Investments',
  'Rental Income',
  'New Immigrants',
];

export const MOCK_CA_DIRECTORY = [
  {
    id: 'ca-001',
    name: 'Amandeep Kaur, CPA',
    title: 'Chartered Professional Accountant',
    specialization: ['Personal Tax', 'Self-Employed', 'Gig Workers'],
    consultationFee: 59,
    filingFeeFrom: 89,
    rating: 4.9,
    reviews: 128,
    languages: ['English', 'Punjabi', 'Hindi'],
    location: 'Calgary, AB',
    nextAvailable: 'Today • 5:30 PM',
    bio: 'Helps employees, self-employed workers, and gig earners with tax planning and filing.',
    avatarIcon: 'account-tie',
    availableSlots: [
      'Today • 5:30 PM',
      'Tomorrow • 10:00 AM',
      'Tomorrow • 3:00 PM',
      'Friday • 1:30 PM',
    ],
  },
  {
    id: 'ca-002',
    name: 'Nadia Chen, CPA',
    title: 'Tax Advisor',
    specialization: ['Personal Tax', 'Investments', 'Rental Income'],
    consultationFee: 75,
    filingFeeFrom: 110,
    rating: 4.8,
    reviews: 94,
    languages: ['English', 'Mandarin'],
    location: 'Edmonton, AB',
    nextAvailable: 'Tomorrow • 11:00 AM',
    bio: 'Focuses on investment income, rental income, and advanced personal returns.',
    avatarIcon: 'briefcase-account-outline',
    availableSlots: [
      'Tomorrow • 11:00 AM',
      'Tomorrow • 4:00 PM',
      'Saturday • 9:00 AM',
    ],
  },
  {
    id: 'ca-003',
    name: 'Ritika Sharma, CPA',
    title: 'Small Business Tax Specialist',
    specialization: ['Small Business', 'Corporate Tax', 'Personal Tax'],
    consultationFee: 95,
    filingFeeFrom: 140,
    rating: 4.9,
    reviews: 173,
    languages: ['English', 'Hindi'],
    location: 'Toronto, ON',
    nextAvailable: 'Thursday • 2:00 PM',
    bio: 'Works with incorporated businesses, owner-managers, and mixed income households.',
    avatarIcon: 'office-building-outline',
    availableSlots: [
      'Thursday • 2:00 PM',
      'Thursday • 5:00 PM',
      'Friday • 10:30 AM',
    ],
  },
];

export const MOCK_ASSIGNED_CA = {
  id: 'ca-001',
  name: 'Amandeep Kaur, CPA',
  title: 'Chartered Professional Accountant',
  specialization: ['Personal Tax', 'Self-Employed', 'Gig Workers'],
  consultationFee: 59,
  filingFeeFrom: 89,
  rating: 4.9,
  reviews: 128,
  languages: ['English', 'Punjabi', 'Hindi'],
  location: 'Calgary, AB',
  nextAvailable: 'Today • 5:30 PM',
  bio: 'Helps employees, self-employed workers, and gig earners with tax planning and filing.',
  avatarIcon: 'account-tie',
};

export const MOCK_APPOINTMENTS = [
  {
    id: 'appt-001',
    caId: 'ca-001',
    caName: 'Amandeep Kaur, CPA',
    type: 'Document Review',
    dateLabel: 'Tomorrow • 10:00 AM',
    status: 'confirmed',
    mode: 'Virtual',
  },
];